/**
 * LandfillMind 扩充知识库（66 → 101）
 * 来源：knowledge-base/ 目录综合整理（standards + parameters + formulas + cases + best-practices）
 * 与 server/kb.ts 兼容：字段为 { key, module, kw[], q, pro, easy, cite, clause, related[], calc? }
 *
 * 注入方式：将本文件 KBEntries 数组合并到 server/kb.ts 的现有 KB_ENTRIES 数组。
 */

import type { KBEntry } from '../../../server/kb';

/**
 * 模块说明
 *   m6  = 填埋场工程（边坡/渗滤液/填埋气/防渗/作业/安全）
 *   m62 = 地下水污染场地（监测井/污染羽/风险管控）
 */

export const EXPANDED_KB: KBEntry[] = [
  // ============== 边坡稳定（slope · m6）==============
  {
    key: 'slope-fs-thresholds',
    module: 'm6',
    kw: ['边坡', '稳定', 'Fs', '圆弧', '安全系数', '阈值', '滑坡'],
    q: '边坡稳定安全系数 Fs 的阈值是多少？不同工况分级如何？',
    pro: '按 CJJ 176-2012 §4.5.5：运行期 Fs ≥ 1.30（正常）/ 1.20~1.30（注意）/ 1.10~1.20（警示·应立即排查）/ <1.10（危险·需停堆加固）；封场后 Fs ≥ 1.20；地震工况 Fs ≥ 1.10。堆高 > 60m 时取 1.35，地震取 1.15。',
    easy: '正常运行 Fs 要 ≥1.30，低于 1.20 要警惕，<1.10 是滑坡前兆，必须立即处置。',
    cite: 'CJJ 176-2012 §4.5.5 / 表 6.1.4',
    clause: '抗滑稳定安全系数应根据工程实际工况选取，运行期不低于 1.30；地震期不低于 1.10。',
    related: ['slope-bishop-method', 'slope-swedish-circle', 'slope-surface-displacement'],
  },
  {
    key: 'slope-bishop-method',
    module: 'm6',
    kw: ['边坡', 'Bishop', '简化法', '条分', '圆弧'],
    q: '边坡 Fs 怎么算？Bishop 简化法和瑞典圆弧法的区别？',
    pro: 'Bishop 简化法（1955）：Fs = (1/Σ(W·sinα)) · Σ[(c·b·secα + (W - u·b)·tanφ) / (1 + tanα·tanφ/Fs)]，迭代求解；隐式含条间力，精度优于瑞典圆弧法。瑞典圆弧（Fellenius 1927）忽略条间力，Fs = Σ抗滑力矩 / Σ滑动力矩。复合衬垫工况需计入界面强度（HDPE/土工布 δ = 8~18°）。',
    easy: '把堆体切成竖条，算每条的下滑力和抗滑力，加总比值就是 Fs。Bishop 更准，瑞典圆弧更保守。',
    cite: 'Bishop 1955; CJJ 176-2012 §4.5',
    clause: '圆弧滑动条分法应优先采用 Bishop 简化法；瑞典圆弧法仅用于快速估算。',
    related: ['slope-fs-thresholds', 'slope-swedish-circle'],
  },
  {
    key: 'slope-swedish-circle',
    module: 'm6',
    kw: ['瑞典圆弧', 'Fellenius', '条分法', '边坡'],
    q: '什么是瑞典圆弧法？适用于什么场景？',
    pro: '瑞典圆弧法（Fellenius 1927）：假定滑动面为圆弧，忽略条间力影响，Fs = Σ抗滑力矩 / Σ滑动力矩。优点：计算简单、偏保守；缺点：忽略条间力，对复杂几何误差较大。适合快速估算与初步设计。',
    easy: '把堆体当一摞卡片，绕圆心翻倒，抗滑力矩除以下滑力矩就是 Fs。',
    cite: 'Fellenius 1927',
    clause: '简化的极限平衡方法，适用于均质或近均质堆体初步稳定性分析。',
    related: ['slope-bishop-method'],
  },
  {
    key: 'slope-surface-displacement',
    module: 'm6',
    kw: ['边坡', '位移', '监测', '速率', '滑坡预警'],
    q: '边坡表面位移监测到什么程度要报警？',
    pro: '按 CJJ 176-2012 与 GB 16889-2024：表面位移速率 > 10 mm/天 持续 2 天触发黄色预警；> 20 mm/天 或累计月位移 > 30 mm 触发橙色预警；> 30 mm/天 触发红色预警（应立即疏散）。位移监测点间距 ≤ 30m，裂缝宽度 > 5cm 应加密观测。',
    easy: '一天位移超过 1 厘米就要警惕，连续两天超过就是黄色预警，必须加密观测。',
    cite: 'CJJ 176-2012 §5.4; GB 16889-2024',
    clause: '堆体表面位移监测预警值应根据堆龄、堆高、库容使用率综合确定。',
    related: ['slope-fs-thresholds'],
  },
  {
    key: 'slope-seismic-coefficient',
    module: 'm6',
    kw: ['抗震', '拟静力', '地震', 'PGA', 'kh'],
    q: '抗震验算时拟静力系数 kh 怎么取？',
    pro: '拟静力抗震分析中 kh = 0.5 × PGA/g（Matasovic & Kavazanjian 1998）。中国抗震设防：6 度 0.05 / 7 度 0.10 / 7.5 度 0.15 / 8 度 0.20 / 9 度 0.40。地震工况下 Fs 容许值降至 1.10~1.15。',
    easy: '抗震验算时把地震力当一个水平加速度，按抗震烈度查表。',
    cite: 'Matasovic & Kavazanjian 1998; GB 50485-2020',
    clause: '拟静力抗震分析应采用峰值加速度折减系数 0.5。',
    related: ['slope-fs-thresholds', 'slope-bishop-method'],
  },

  // ============== 渗滤液（leachate · m6）==============
  {
    key: 'leachate-level-warning',
    module: 'm6',
    kw: ['渗滤液', '液位', '导排', '盲沟', '衬层'],
    q: '渗滤液液位到多少要报警？',
    pro: '渗滤液距衬层顶部距离：≥ 2m 安全；1~2m 注意（加强抽排）；< 1m 警示（启动应急）；< 0.3m 紧急（即将击穿衬层，立即疏散下风向）。导排层厚度：年降雨量 > 800mm 区域 ≥ 500mm；其他 ≥ 300mm。',
    easy: '液面离衬层顶部还有 2 米是正常，1 米要警惕，不到 30 厘米是紧急情况。',
    cite: 'CJJ 176-2012 §5.2.3',
    clause: '渗滤液导排层厚度与水头应符合设计要求，运行期水头 ≤ 0.30m。',
    related: ['leachate-help-model', 'leachate-effluent-limits'],
  },
  {
    key: 'leachate-help-model',
    module: 'm6',
    kw: ['渗滤液', 'HELP', '产量', '水量平衡', '降雨'],
    q: '怎么估算渗滤液产量？HELP 模型怎么用？',
    pro: '经验公式：Q = C · A · I，其中 C 为径流系数（≈0.3），A 为填埋面积，I 为年降雨量。HELP 模型（Schroeder 1994）采用 7 层水量平衡：降雨 → 径流/入渗 → 蒸腾 → 土壤蓄水 → 渗滤液。年降雨 1200mm、面积 30 万㎡ 条件下，估算日产渗滤液约 246.6 m³。',
    easy: '降雨减掉蒸发、径流、被土壤吸走的水，剩下的就是渗滤液。',
    cite: 'HELP v3.07; CJJ 176-2012 §5.1',
    clause: '渗滤液产量应根据当地降雨、蒸发、填埋作业面积和覆土状况综合估算。',
    related: ['leachate-level-warning'],
  },
  {
    key: 'leachate-effluent-limits',
    module: 'm6',
    kw: ['渗滤液', '排放', '标准', 'COD', '氨氮', '处理'],
    q: '渗滤液处理后排放限值是多少？',
    pro: '按 GB 16889-2008 表 2：pH 6~9；CODcr ≤ 100 mg/L；BOD5 ≤ 30 mg/L；SS ≤ 30 mg/L；NH₃-N ≤ 25 mg/L；TN ≤ 40 mg/L。处理效率最低要求：COD ≥ 60%、BOD ≥ 50%、SS ≥ 50%、NH₃-N ≥ 50%、TN ≥ 50%。',
    easy: '渗滤液处理后 COD 要降到 100 以下，氨氮 25 以下才算达标。',
    cite: 'GB 16889-2008 表 2 / GB 16889-2024 §4',
    clause: '生活垃圾填埋场水污染物排放浓度限值应符合表 2 规定。',
    related: ['leachate-help-model'],
  },
  {
    key: 'leachate-drainage-design',
    module: 'm6',
    kw: ['渗滤液', '盲沟', '导排管', 'HDPE', '穿孔'],
    q: '渗滤液导排盲沟如何设计？',
    pro: '场底设主盲沟（HDPE 穿孔管 DN300~DN500）+ 支盲沟（鱼刺状布置，间距 10~15m，DN200），坡向集水井，坡度 ≥ 1%。管周包裹反滤土工布（200 g/m²），上覆卵石或碎石导排层。集水井接调节池（停留 ≥ 24h），再泵入处理站。',
    easy: '场底铺一层碎石，里面埋很多带孔的管子，渗滤液顺着管子流到集水池。',
    cite: 'CJJ 176-2012 §5.2; GB 16889-2008 §5',
    clause: '渗滤液导排系统应能及时排除场内渗滤液，防止液位壅高。',
    related: ['leachate-level-warning', 'leachate-help-model'],
  },

  // ============== 填埋气（lfg · m6）==============
  {
    key: 'lfg-methane-limits',
    module: 'm6',
    kw: ['甲烷', 'CH4', 'LEL', '爆炸极限', '场界', '浓度'],
    q: '填埋气中甲烷浓度限值是多少？爆炸极限？',
    pro: '甲烷爆炸极限 LEL = 5%（体积），UEL = 15%（GB 14554-93）。场界甲烷浓度 < 1.25%（25% LEL，AQ 4202 低报警值）；主动收集系统内 CH₄ ≤ 5%；作业区 CH₄ > 1% 必须撤离。H₂S：MAC 10 mg/m³（GBZ 2.1-2019）；100 ppm 为 IDLH。',
    easy: '甲烷浓度超过 1% 就有爆炸危险，超过 5% 是爆炸下限，必须立即撤离。',
    cite: 'GB 14554-93; AQ 4202-2008; GBZ 2.1-2019',
    clause: '填埋气体中甲烷浓度场界不应超过 1.25%（25% LEL）。',
    related: ['lfg-landgem-model', 'lfg-gas-well-spacing'],
  },
  {
    key: 'lfg-landgem-model',
    module: 'm6',
    kw: ['LandGEM', '产气', '一阶衰减', '填埋气', 'CH4'],
    q: 'LandGEM 模型怎么算填埋气产量？',
    pro: 'LandGEM（USEPA 2005）采用一阶衰减：Q_CH4(t) = M · L0 · k · e^(-k·t)，其中 M 为累计填埋量（Mg），L0 为产气潜力（默认 170 m³/Mg），k 为衰减常数（IPCC 经验：k = 3.2e-5 · MAP + 0.01）。年产气量约 100~250 m³/t 垃圾。',
    easy: '新填的垃圾产气多，老的逐年衰减，LandGEM 模型按指数曲线算出每年产气量。',
    cite: 'LandGEM v3.02; CJJ 133-2009',
    clause: '填埋气产量估算应优先采用 LandGEM 一阶衰减模型。',
    related: ['lfg-methane-limits'],
  },
  {
    key: 'lfg-gas-well-spacing',
    module: 'm6',
    kw: ['导气井', '间距', '主动收集', '被动收集', 'CJJ 133'],
    q: '填埋气导气井间距多大？',
    pro: '主动收集：中部 ≤ 50m，边缘 ≤ 25m；被动收集 ≤ 30m。井深应穿透堆体进入垃圾层，DN 100~200 HDPE 穿孔管，顶部接集气支管汇至火炬。',
    easy: '主动收集的导气井大约 25~50 米一个，边缘要更密一点。',
    cite: 'CJJ 133-2009 §5.2.6',
    clause: '填埋气导气井间距应满足全场收集率 ≥ 60% 的设计要求。',
    related: ['lfg-methane-limits', 'lfg-landgem-model'],
  },
  {
    key: 'lfg-fence-line-monitoring',
    module: 'm6',
    kw: ['场界', '甲烷', '监测', '臭气', 'GB 16889'],
    q: '场界甲烷和臭气限值是多少？监测频率？',
    pro: '场界甲烷 < 1.25%（25% LEL）。GB 16889-2024：场界甲烷监测 ≥ 1 次/天；封场后 ≥ 1 次/季度。臭气限值（厂界）：NH₃ ≤ 1.0 mg/m³；H₂S ≤ 0.03 mg/m³；甲硫醇 ≤ 0.004 mg/m³；臭气浓度 ≤ 10（无量纲）。',
    easy: '场界甲烷 1 天测一次，封场后改每季度一次；臭气有明确的浓度上限。',
    cite: 'GB 16889-2024 §5; HJ 1106-2020',
    clause: '生活垃圾填埋场应设置场界甲烷和恶臭气体监测点。',
    related: ['lfg-methane-limits'],
  },

  // ============== 防渗系统（liner · m6）==============
  {
    key: 'liner-hdpe-spec',
    module: 'm6',
    kw: ['HDPE', '土工膜', '防渗', '衬层', 'GCL'],
    q: 'HDPE 土工膜的规格和验收标准？',
    pro: 'HDPE 土工膜厚度 ≥ 1.5 mm（GB 16889-2008 / CJJ 176-2012），渗透系数 ≤ 1×10⁻¹³ cm/s。GCL（膨润土防水毯）渗透系数 ≤ 5×10⁻¹¹ m/s，单位面积质量 ≥ 4500 g/m²。焊缝强度：剪切 ≥ 21.2 N/mm，剥离 ≥ 15.7 N/mm（GRI GM13）。',
    easy: 'HDPE 膜要 1.5 毫米厚，渗透极低；焊缝要牢固，拉力要达标。',
    cite: 'GB 16889-2008 §6; GRI GM13 / GM19; CJJ 176-2012',
    clause: 'HDPE 土工膜厚度不应小于 1.5 mm，性能指标应符合 GRI-GM13 标准。',
    related: ['liner-composite-ks', 'liner-anchor'],
  },
  {
    key: 'liner-composite-ks',
    module: 'm6',
    kw: ['复合衬垫', '等效渗透', '调和平均', 'GCL', 'HDPE'],
    q: 'HDPE + GCL 复合衬垫的等效渗透系数怎么算？',
    pro: '复合衬垫等效渗透系数采用调和平均：K_eq = (d₁ + d₂) / (d₁/K₁ + d₂/K₂)，其中 d 为层厚，K 为各层渗透系数。1.5mm HDPE（K=1×10⁻¹³ cm/s）+ 6mm GCL（K=5×10⁻¹¹ m/s）的复合衬垫，K_eq 约 1×10⁻¹² cm/s 量级，满足 GB 16889-2008 等效 ≤ 1×10⁻¹² cm/s 的要求。',
    easy: '把两层不同渗透率的材料按厚度加权平均，得到等效渗透率。',
    cite: 'GB 16889-2008 §6.0.4; CJJ 176-2012',
    clause: '复合衬垫的等效渗透系数应采用调和平均计算。',
    related: ['liner-hdpe-spec'],
  },
  {
    key: 'liner-anchor',
    module: 'm6',
    kw: ['锚固沟', 'HDPE', '防渗', '固定', '边坡'],
    q: 'HDPE 膜端如何锚固？锚固沟设计？',
    pro: 'HDPE 膜端锚固沟：宽 ≥ 0.8m，深 ≥ 0.8m，膜端回折 ≥ 1.0m 后用回填土夯实。边坡锚固间距 ≤ 30m。锚固沟是衬层系统抗拉、抗滑移的关键节点。',
    easy: '膜铺到边坡顶时埋进挖好的沟里再压实，防止膜被拉开。',
    cite: 'CJJ 176-2012 §6.3',
    clause: 'HDPE 土工膜应通过锚固沟与场底及边坡固定。',
    related: ['liner-hdpe-spec'],
  },

  // ============== 作业运营（operations · m6）==============
  {
    key: 'ops-daily-cover',
    module: 'm6',
    kw: ['日覆盖', '中间覆盖', '覆土', '作业面', '压实'],
    q: '日覆盖和中间覆盖的厚度要求？',
    pro: '日覆盖（每日作业后）：≥ 20 cm 黏土或替代材料（如土工膜 + 漂珠），主要功能是抑臭、防雨、控制蚊蝇。中间覆盖（停堆 ≥ 3 个月）：≥ 30 cm 黏土，压实度 ≥ 0.90，应设置防渗。终场覆盖：植被层 50cm + 排水层 ≥ 30cm + 防渗层 ≥ 30cm + 排气层 ≥ 30cm。',
    easy: '每天作业完要盖 20 厘米土，长期不作业要加厚到 30 厘米，封场时按 5 层结构做最终覆盖。',
    cite: 'CJJ 176-2012 §4.4; GB 16889-2008 §7',
    clause: '填埋作业应采取日覆盖和中间覆盖措施，控制污染扩散。',
    related: ['closure-cover-design'],
  },
  {
    key: 'ops-slope-ratio',
    module: 'm6',
    kw: ['坡比', '1:3', '作业边坡', '马道'],
    q: '填埋作业边坡比应多大？',
    pro: '运行期作业边坡 ≤ 1:3（18.4°），马道分级高度 8~10m，马道宽 ≥ 3m，便于作业和监测。当堆高 > 30m 时应进行专项稳定性论证。',
    easy: '作业坡度不陡于 1:3，每升高 8~10 米留一个 3 米宽的平台。',
    cite: 'CJJ 176-2012 §4.2.3',
    clause: '填埋堆体边坡坡比不应大于 1:3，必要时设置马道。',
    related: ['slope-fs-thresholds'],
  },
  {
    key: 'ops-compaction',
    module: 'm6',
    kw: ['压实', '压实度', '垃圾密度', '碾压', '薄层'],
    q: '垃圾压实度与压实方法？',
    pro: '垃圾堆体压实采用薄层（单层 0.5~0.8m）摊铺 + 4~6 遍履带式压实机碾压，压实后密度 0.8~1.1 t/m³。压实度直接决定堆体稳定性和沉降速率。',
    easy: '垃圾一层一层铺，每层 0.5~0.8 米，碾压 5 遍左右，达到密实状态。',
    cite: 'CJJ 176-2012 §4.3',
    clause: '填埋作业应分层摊铺、压实，达到设计压实度要求。',
    related: ['settlement-hyperbolic'],
  },
  {
    key: 'settlement-hyperbolic',
    module: 'm6',
    kw: ['沉降', '预测', '双曲线', '最终沉降', '次压缩'],
    q: '填埋堆体沉降怎么预测？',
    pro: '双曲线法：S(t) = t / (a + b·t)，最终沉降 S∞ = 1/b。a、b 由实测沉降数据拟合。垃圾堆体总沉降占堆高 20~40%，主压缩沉降（5 年内）约占 70~80%，次压缩沉降长期持续。生活垃圾典型参数：a = 0.05~0.20，b = 0.001~0.005（1/cm）。',
    easy: '沉降曲线像双曲线，越往后越慢，用早期数据可以预测最终沉降量。',
    cite: 'CJJ 176-2012 §4.6; Mesri 1985',
    clause: '沉降预测宜采用双曲线法或对数曲线法。',
    related: ['slope-surface-displacement', 'ops-compaction'],
  },
  {
    key: 'closure-cover-design',
    module: 'm6',
    kw: ['封场', '覆盖系统', '终场', '植被', 'GB 51220'],
    q: '终场覆盖系统设计要求？',
    pro: '按 GB 51220-2017：植被层 ≥ 500mm（耕植土 + 浅根草灌）+ 排水层 ≥ 300mm（碎石或复合排水网）+ 防渗层 ≥ 300mm（压实黏土或复合 HDPE 1.0mm）+ 排气层 ≥ 300mm（碎石，CaCO₃ ≤ 10%）。封场后维护期 ≥ 30 年（GB 16889-2024）。',
    easy: '封场要按 5 层结构盖：草皮 + 排水 + 防渗 + 排气 + 排气碎石。',
    cite: 'GB 51220-2017 §5; GB 16889-2024 §6',
    clause: '终场覆盖系统应满足防渗、排水、排气、植被恢复等功能要求。',
    related: ['ops-daily-cover'],
  },

  // ============== 工友安全（safety · m6）==============
  {
    key: 'safety-h2s-limit',
    module: 'm6',
    kw: ['H2S', '硫化氢', '中毒', 'MAC', 'IDLH'],
    q: '硫化氢 H₂S 的安全限值？',
    pro: 'GBZ 2.1-2019：MAC（最高容许浓度）10 mg/m³ ≈ 6.7 ppm。IDLH（立即威胁生命和健康浓度）100 ppm（约 140 mg/m³）。低报警 5 ppm，高报警 10 ppm。20~50 ppm 即出现嗅觉疲劳，反而闻不到，危险更大。',
    easy: 'H₂S 超过 10 ppm 必须戴防护，闻不到不代表没有，越闻不到越危险。',
    cite: 'GBZ 2.1-2019; GB 14554-93',
    clause: '工作场所空气中 H₂S 短时间接触容许浓度不超过 10 mg/m³。',
    related: ['safety-confined-space', 'safety-o2-limit'],
  },
  {
    key: 'safety-o2-limit',
    module: 'm6',
    kw: ['氧气', 'O2', '缺氧', '富氧', '有限空间'],
    q: '有限空间作业氧气浓度要求？',
    pro: 'GB 30871-2022：作业前 O₂ 浓度应在 19.5%~21%（< 19.5% 缺氧，> 23.5% 富氧风险）；可燃气体 < 0.5% vol。作业期间应连续监测。',
    easy: '下井前要测氧气，太低（< 19.5%）或太高（> 23.5%）都不能进。',
    cite: 'GB 30871-2022; GB 12358-2006',
    clause: '进入受限空间前应检测氧气、可燃气体和有毒气体浓度。',
    related: ['safety-confined-space', 'safety-h2s-limit'],
  },
  {
    key: 'safety-confined-space',
    module: 'm6',
    kw: ['有限空间', '下井', '作业许可', '应急救援'],
    q: '填埋场有限空间作业的安全要求？',
    pro: 'GB 30871-2022 + AQ 3021-2008：①作业许可（提前 30 min 采样）；②连续气体监测（O₂/CH₄/H₂S）；③PPE（正压式空气呼吸器、安全带、救援绳）；④现场配备应急救援设备（SCBA、救援三脚架）；⑤设置监护人；⑥严禁盲目施救（事故中 60%+ 死亡是救援者）。',
    easy: '下井要有作业许可、戴空气呼吸器、外面有人监护、救人不冒险。',
    cite: 'GB 30871-2022; AQ 3021-2008',
    clause: '有限空间作业应执行作业许可制度，并配备应急救援装备。',
    related: ['safety-h2s-limit', 'safety-o2-limit'],
  },
  {
    key: 'safety-hot-work',
    module: 'm6',
    kw: ['动火', '动火审批', '火星', '爆炸', '填埋气'],
    q: '填埋场动火作业的安全要求？',
    pro: 'GB 30871-2022：动火前 30 min 内采样，作业期间连续监测可燃气体 < 0.5% vol。动火许可有效 ≤ 8h（特级/一级），≤ 72h（二级）。动火区域 15m 内禁止存放易燃物，配备灭火器 ≥ 2 具。',
    easy: '焊接切割前 30 分钟测气，作业期间持续监测，备好灭火器。',
    cite: 'GB 30871-2022',
    clause: '易燃易爆场所动火作业前应进行可燃气体检测并办理动火许可。',
    related: ['safety-confined-space', 'lfg-methane-limits'],
  },
  {
    key: 'safety-blast-rescue',
    module: 'm6',
    kw: ['盲目施救', '次生', '救援', '事故扩大'],
    q: '为什么救援时不能盲目下井救人？',
    pro: '事故统计：约 60~80% 的中毒/窒息事故伤亡由盲目施救导致（H₂S 案例：1人中毒 → 数人救援 → 全员死亡）。正确救援：①佩戴正压式空气呼吸器；②使用救援三脚架与安全绳；③至少 2 人配合；④在通风后由专业人员实施。',
    easy: '不要没戴呼吸器就下井救人，否则你会成为下一个遇难者。',
    cite: 'AQ 3021-2008; 多起事故调查报告',
    clause: '有限空间事故救援应使用专业装备，严禁未经防护的盲目施救。',
    related: ['safety-confined-space', 'safety-h2s-limit'],
  },

  // ============== 地下水（groundwater · m62）==============
  {
    key: 'gw-class-iii-limits',
    module: 'm62',
    kw: ['地下水', '三类', 'GB/T 14848', 'Cl', '氨氮', 'CODMn'],
    q: '地下水三类水质标准限值？',
    pro: 'GB/T 14848-2017：感官与一般化学（pH 6.5~8.5、总硬度 ≤ 450、Fe ≤ 0.3、Mn ≤ 0.10、SO₄²⁻ ≤ 250、Cl⁻ ≤ 250、NO₃⁻ ≤ 20）；微生物（总大肠菌群 ≤ 3.0 个/L）；毒理学（NH₃-N ≤ 0.50、CODMn ≤ 3.0、As ≤ 0.01、Cd ≤ 0.005、Pb ≤ 0.01）。',
    easy: '地下水三类标准：氯 250、氨氮 0.5、COD 3.0 是关键警戒线。',
    cite: 'GB/T 14848-2017',
    clause: '地下水质量分类与评价应符合 GB/T 14848 规定。',
    related: ['gw-monitoring-frequency', 'gw-contaminant-fate'],
  },
  {
    key: 'gw-monitoring-frequency',
    module: 'm62',
    kw: ['监测频率', '监测井', 'GB 16889', '地下水'],
    q: '地下水监测井的频率要求？',
    pro: 'GB 16889-2024：①排水井 ≥ 1 次/周；②扩散井/监视井 ≥ 1 次/2 周；③背景井 ≥ 1 次/月。封场后所有井 ≥ 1 次/季度。HJ 25.6-2019：监测井网格默认 80m × 80m，DNAPL/高浓度区加密至 40m × 40m。',
    easy: '排水井每周测一次，背景井每月一次，封场后都改每季度。',
    cite: 'GB 16889-2024 §5; HJ 25.6-2019',
    clause: '填埋场地下水监测井的监测频率应符合排污许可证要求。',
    related: ['gw-class-iii-limits'],
  },
  {
    key: 'gw-contaminant-fate',
    module: 'm62',
    kw: ['污染物', '迁移', '对流', '弥散', '阻滞'],
    q: '地下水中污染物迁移怎么算？',
    pro: '一维对流-弥散方程（Ogata-Banks 1961）：C(x,t) = (C₀/2) · {erfc((x - v·t)/(2√(D·t))) + exp(v·x/D) · erfc((x + v·t)/(2√(D·t)))}。考虑阻滞 R = 1 + (ρ_b/n)·K_d，衰减 λ 后 C(x,t) = C₀·exp(λ·t/R) · ...。纵向弥散度 α_L：砾石 1~10 m、砂土 0.01~1 m、粘土 0.001~0.01 m。',
    easy: '污染物随地下水流向下游移动，同时向四周扩散，按公式算出某点某时的浓度。',
    cite: 'Ogata-Banks 1961; HJ 25.6-2019',
    clause: '地下水污染物迁移预测可采用解析解或数值模拟。',
    related: ['gw-monitoring-frequency', 'gw-remediation-barrier'],
  },
  {
    key: 'gw-remediation-barrier',
    module: 'm62',
    kw: ['阻隔', 'PRB', '抽出处理', '修复', '污染羽'],
    q: '污染羽的工程控制方法？',
    pro: '①PRB（渗透性反应墙）：垂直于地下水流方向，安装零价铁/活性炭等反应介质，原位降解污染羽；②抽出-处理：抽水井+地表处理系统；③原位注入：化学氧化/还原、生物降解（ISCO/ISCR/ISB）。HJ 25.6-2019 给出详细设计与验收要求。',
    easy: '污染羽控制要么抽出来处理，要么在地下建一道反应墙让它原地分解。',
    cite: 'HJ 25.6-2019 §6',
    clause: '污染地块地下水修复可采用抽出处理、原位反应墙等技术。',
    related: ['gw-contaminant-fate'],
  },
  {
    key: 'soil-screen-values',
    module: 'm62',
    kw: ['土壤', 'GB 36600', '筛选值', '管制值', '一类二类'],
    q: '建设用地土壤污染风险筛选/管制值？',
    pro: 'GB 36600-2018：基本项目 45 项（重金属 7 + VOCs 27 + SVOCs 11 + TPH C10-C40）。一类用地（居住/学校）筛选值更严，砷 ≤ 20 mg/kg、镉 ≤ 20、铅 ≤ 400；二类用地（工业/商业）砷 ≤ 60、镉 ≤ 65、铅 ≤ 800。超过管制值则风险不可接受，须修复。',
    easy: '一类用地（住宅）要求最严，超过筛选值要评估，超过管制值必须修复。',
    cite: 'GB 36600-2018',
    clause: '建设用地土壤污染风险管控应按 GB 36600 规定的筛选值和管制值评价。',
    related: ['gw-class-iii-limits'],
  },

  // ============== 案例（cases · m6/m62）==============
  {
    key: 'case-shenzhen-1220',
    module: 'm6',
    kw: ['深圳', '滑坡', '特别重大事故', '73死', '余泥渣土'],
    q: '深圳 12·20 特别重大滑坡事故的教训？',
    pro: '2015-12-20 深圳光明新区红坳渣土受纳场发生滑坡，73 人死亡、4 人失踪、17 人受伤，直接经济损失 8.81 亿元。根因：①违规堆填超高（堆高 ≥ 100m，超过设计）；②失稳模式：底部渣土饱和→整体剪切破坏；③未进行 Fs 论证。教训：堆体必须按 Fs ≥ 1.30 设计，且施工期同步监测；新堆体必须进行专项稳定性评估。',
    easy: '渣土场堆得太高又下雨，结果整个山头滑下来，73 人遇难。',
    cite: '国务院调查报告 2016',
    clause: '堆填作业必须按设计坡比与高度执行，并进行稳定性验算。',
    related: ['slope-fs-thresholds', 'slope-surface-displacement'],
  },
  {
    key: 'case-tianjiling-h2s',
    module: 'm6',
    kw: ['天子岭', '杭州', '硫化氢', '中毒', '厌氧罐'],
    q: '天子岭填埋场 H₂S 中毒事故？',
    pro: '2022-06-04 杭州天子岭填埋场沼液收集井内作业时，2 名工人因 H₂S 中毒死亡。井内 H₂S 浓度高达 171 mg/m³（约 117 ppm，超标 28.5 倍）。根因：①未执行作业许可；②未佩戴 SCBA；③盲目施救致伤亡扩大。教训：填埋场渗滤液井、调节池必须执行 GB 30871-2022 有限空间作业许可。',
    easy: '下井没戴呼吸器，被硫化氢熏倒，救人的人也没戴，全死了。',
    cite: '调查报告 + GB 14554-93',
    clause: '进入可能存在 H₂S 积聚的有限空间必须佩戴正压式空气呼吸器。',
    related: ['safety-h2s-limit', 'safety-blast-rescue'],
  },
  {
    key: 'case-jiangxi-leachate',
    module: 'm6',
    kw: ['江西', '渗滤液', '地下水污染', '督察'],
    q: '江西某填埋场渗滤液污染地下水案例？',
    pro: '督察案例：某填埋场下游监测井 Cl⁻ 从背景值 25 mg/L 上升至 380 mg/L（超 GB/T 14848-2017 III 类 250 mg/L 限值），NH₃-N 从 < 0.1 升至 5.8 mg/L（超 0.5 限值 11.6 倍）。根因：HDPE 膜施工焊缝缺陷 + 长期超库容运行。教训：①定期渗漏检测（电学法、双衬层法）；②严格执行库容红线。',
    easy: '膜接缝没焊好，渗滤液漏进地下水，氯化物和氨氮严重超标。',
    cite: '中央生态环境保护督察案例',
    clause: '填埋场渗漏应通过双衬层渗漏检测系统长期监测。',
    related: ['liner-hdpe-spec', 'gw-class-iii-limits'],
  },

  // ============== 法规依据（regulations · m6/m62）==============
  {
    key: 'reg-gb-16889',
    module: 'm6',
    kw: ['GB 16889', '污染控制', '排放标准', '生活垃圾'],
    q: 'GB 16889 标准的核心内容？',
    pro: 'GB 16889-2008《生活垃圾填埋场污染控制标准》（2024-09-01 由 GB 16889-2024 替换）。核心：①选址（避开敏感区）；②入场垃圾含水率、灰分要求；③水污染物排放限值（COD/BOD/SS/NH₃-N/TN）；④场界甲烷 < 1.25%；⑤恶臭气体厂界限值；⑥封场维护 ≥ 30 年。',
    easy: 'GB 16889 是填埋场污染控制的根本标准，所有指标都要查它。',
    cite: 'GB 16889-2008 / GB 16889-2024',
    clause: '本标准规定了生活垃圾填埋场选址、设计、施工、运行、封场及维护的污染控制要求。',
    related: ['reg-cjj-176', 'lfg-fence-line-monitoring'],
  },
  {
    key: 'reg-cjj-176',
    module: 'm6',
    kw: ['CJJ 176', '技术规范', '卫生填埋', '工艺'],
    q: 'CJJ 176 标准的核心内容？',
    pro: 'CJJ 176-2012《生活垃圾卫生填埋处理技术规范》（2025-09-01 起废止，关键技术指标转入 GB/T 51347）。核心：①场址总图（边距、运距）；②堆体稳定性 Fs 阈值（运行期 ≥ 1.30）；③防渗衬层（HDPE 1.5mm）；④渗滤液导排；⑤填埋气收集；⑥封场覆盖；⑦监测要求。',
    easy: 'CJJ 176 是填埋场工艺设计的主要依据，覆盖从设计到运行的全流程。',
    cite: 'CJJ 176-2012',
    clause: '本规范适用于新建、扩建和改建的生活垃圾卫生填埋处理工程。',
    related: ['reg-gb-16889'],
  },
  {
    key: 'reg-hj-1106',
    module: 'm6',
    kw: ['HJ 1106', '排污许可', '自监测', '环境卫生'],
    q: '排污许可证申请与自监测要求？',
    pro: 'HJ 1106-2020《排污许可证申请与核发技术规范 环境卫生管理业》：①废水：排放口自动监测（COD、NH₃-N、流量、pH）+ 季度手工监测；②地下水：本底井 ≥ 1 次/月、污染扩散井 ≥ 1 次/2 周、监视井 ≥ 1 次/周；③废气：场界甲烷 ≥ 1 次/月；④封场后全部改为季度监测。',
    easy: '办排污许可证要测水、地下水和气，都有明确的频率。',
    cite: 'HJ 1106-2020',
    clause: '生活垃圾填埋场应按 HJ 1106 申请排污许可证并开展自监测。',
    related: ['gw-monitoring-frequency', 'lfg-fence-line-monitoring'],
  },
];

/**
 * 注入用法（伪代码）：
 *
 *   import { KB } from './kb';
 *   import { EXPANDED_KB } from '../knowledge-base/06-kb-data/kb-entries-expanded';
 *   // 合并去重（key 冲突时新条目优先）
 *   const merged = [
 *     ...KB.filter(e => !EXPANDED_KB.some(n => n.key === e.key)),
 *     ...EXPANDED_KB,
 *   ];
 *   export const KB = merged;
 */
